### ISSUE TITLE
Weird Path.arc results 

### ISSUE THREAD

**Issue by mmmintdesign** [baku89/pathed#1]
I noticed that the arc breaks or gets drawn wrong with specific angles. 
Some examples are: 
`Path.arc([20, 40], 10, 0.3217505543966421, -2.819842099193151)`
`Path.arc([40, 40], 10, -1.82, 1.33)`

**Comment by baku89** [comment]
Thank you for reporting the issue. I'll see what's wrong with the library and refactor it then;)

**Comment by mmmintdesign** [comment]
Pull request #2 should fix the main bug.

In case of ([40, 40], 10, -1.82, 1.33).
It seems like while loop adds a second A path, which adds up to 2 Arcs [M A A].
Not sure if this is intended, but doesn't seem to affect the rendering.
